---
secrets:
  enabled: true
  entropy_threshold: 4.5
  custom_patterns:
    - name: "Internal API Token"
      pattern: "INT-[A-Z0-9]{32}"
      severity: "CRITICAL"
      description: "Internal API token detected"
    
    - name: "Database Connection String"
      pattern: "(?i)(mongodb|mysql|postgres)://[^\\s]+"
      severity: "HIGH"
      description: "Database connection string detected"

policies:
  enabled: true
  disallow_modules:
    - shell
    - command
    - raw
    - script
  require_vault: true

linting:
  enabled: true
  severity_threshold: "medium"

general:
  exclude_paths:
    - ".git"
    - "venv"
    - ".venv"
    - "node_modules"
    - "test"
    - ".pytest_cache"
  max_file_size: 10485760  # 10MB
  cache_dir: ".ansiblesec_cache"
