---
collections:
  - name: community.general
    version: ">=6.0.0"
  - name: ansible.posix
    version: "1.5.0"
  - name: community.docker
    version: "3.4.0"

roles:
  - name: geerlingguy.nginx
    version: "3.1.0"
  - src: https://github.com/geerlingguy/ansible-role-docker
    version: "6.0.0"
    name: geerlingguy.docker
